#!/usr/bin/env ansible-playbook

- name: 'deploy e-cidade discourse'
  hosts: all
  become: true
  gather_facts: false
  strategy: free
  roles:
    - role: discourse
      vars:
        DISCOURSE_HOST: "{{ lookup('ansible.builtin.env', 'TARGET_DOMAIN') }}"
        DISCOURSE_DOCKER_IMAGE: docker.io/bitnami/discourse:2.8.6
        REDIS_DOCKER_IMAGE: docker.io/bitnami/redis:6.2