# https://taskfile.dev

version: '3'

vars:
  STAGE: development

tasks:
  secret:view:
    desc: Exibe o conteúdo do arquivo de segredos
    cmds:
      - ansible-vault view vars/.secrets.{{ .STAGE }}.yml

  secret:edit:
    desc: Edita o conteúdo do arquivo de segredos
    cmds:
      - ansible-vault edit vars/.secrets.{{ .STAGE }}.yml

  inventory:
    desc: Gera o arquivo de inventário do ansible
    cmds:
      - NODE_ENV={{ .STAGE }} node scripts/generate-inventary.mjs > inventory.{{ .STAGE }}.ini

  deploy:discourse:
    desc: faz deploy do e-Cidade discourse
    cmds:
    - |
      ansible-playbook discourse.yml -v \
        --inventory-file inventory.{{ .STAGE }}.ini \
        --extra-vars "@vars/{{ .STAGE }}.yml" \
        --extra-vars "@vars/.secrets.{{ .STAGE }}.yml" {{.CLI_ARGS}}
